"""Initial migration

Revision ID: a2a1dd9e6740
Revises: 
Create Date: 2024-11-26 11:58:53.996807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a1dd9e6740'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('is_recruiter', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vacancies',
    sa.Column('vacancyId', sa.Integer(), nullable=False),
    sa.Column('jobTitle', sa.String(length=500), nullable=False),
    sa.Column('jobDescription', sa.String(length=1000), nullable=False),
    sa.Column('jobLocation', sa.String(length=500), nullable=False),
    sa.Column('jobPayRate', sa.String(length=120), nullable=False),
    sa.Column('maxHoursAllowed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('vacancyId')
    )
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacancies_jobDescription'), ['jobDescription'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_jobLocation'), ['jobLocation'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_jobPayRate'), ['jobPayRate'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_jobTitle'), ['jobTitle'], unique=False)

    op.create_table('job_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_link', sa.String(length=255), nullable=False),
    sa.Column('applied_on', sa.Date(), nullable=False),
    sa.Column('last_update_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiter_postings',
    sa.Column('postingId', sa.Integer(), nullable=False),
    sa.Column('recruiterId', sa.Integer(), nullable=False),
    sa.Column('jobTitle', sa.String(length=500), nullable=False),
    sa.Column('jobDescription', sa.String(length=1000), nullable=False),
    sa.Column('jobLink', sa.String(length=1000), nullable=False),
    sa.Column('jobLocation', sa.String(length=500), nullable=False),
    sa.Column('jobPayRate', sa.String(length=120), nullable=False),
    sa.Column('maxHoursAllowed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recruiterId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('postingId')
    )
    with op.batch_alter_table('recruiter_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruiter_postings_jobDescription'), ['jobDescription'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruiter_postings_jobLink'), ['jobLink'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruiter_postings_jobLocation'), ['jobLocation'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruiter_postings_jobPayRate'), ['jobPayRate'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruiter_postings_jobTitle'), ['jobTitle'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('locations', sa.String(length=120), nullable=False),
    sa.Column('job_title', sa.String(length=64), nullable=False),
    sa.Column('job_description', sa.String(length=120), nullable=False),
    sa.Column('hourly_pay', sa.String(length=10), nullable=False),
    sa.Column('benefits', sa.String(length=120), nullable=False),
    sa.Column('review', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_benefits'), ['benefits'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_job_description'), ['job_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_job_title'), ['job_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_locations'), ['locations'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_review'), ['review'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('meeting_time', sa.DateTime(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['recruiter_postings.postingId'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posting_applications',
    sa.Column('postingId', sa.Integer(), nullable=False),
    sa.Column('recruiterId', sa.Integer(), nullable=False),
    sa.Column('applicantId', sa.Integer(), nullable=False),
    sa.Column('shortlisted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['applicantId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['postingId'], ['recruiter_postings.postingId'], ),
    sa.ForeignKeyConstraint(['recruiterId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('postingId', 'recruiterId', 'applicantId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posting_applications')
    op.drop_table('meetings')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_review'))
        batch_op.drop_index(batch_op.f('ix_reviews_locations'))
        batch_op.drop_index(batch_op.f('ix_reviews_job_title'))
        batch_op.drop_index(batch_op.f('ix_reviews_job_description'))
        batch_op.drop_index(batch_op.f('ix_reviews_department'))
        batch_op.drop_index(batch_op.f('ix_reviews_benefits'))

    op.drop_table('reviews')
    with op.batch_alter_table('recruiter_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruiter_postings_jobTitle'))
        batch_op.drop_index(batch_op.f('ix_recruiter_postings_jobPayRate'))
        batch_op.drop_index(batch_op.f('ix_recruiter_postings_jobLocation'))
        batch_op.drop_index(batch_op.f('ix_recruiter_postings_jobLink'))
        batch_op.drop_index(batch_op.f('ix_recruiter_postings_jobDescription'))

    op.drop_table('recruiter_postings')
    op.drop_table('job_experience')
    op.drop_table('job_application')
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancies_jobTitle'))
        batch_op.drop_index(batch_op.f('ix_vacancies_jobPayRate'))
        batch_op.drop_index(batch_op.f('ix_vacancies_jobLocation'))
        batch_op.drop_index(batch_op.f('ix_vacancies_jobDescription'))

    op.drop_table('vacancies')
    op.drop_table('user')
    # ### end Alembic commands ###
