"""added new posting_applicant table

Revision ID: b9b8a925d519
Revises: f46fb8558e7e
Create Date: 2024-11-19 16:14:24.534669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b8a925d519'
down_revision = 'f46fb8558e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posting_applications',
    sa.Column('postingId', sa.Integer(), nullable=False),
    sa.Column('recruiterId', sa.Integer(), nullable=False),
    sa.Column('applicantId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicantId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recruiterId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('postingId', 'recruiterId', 'applicantId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posting_applications')
    # ### end Alembic commands ###
