"""Added new recruiters_posting table

Revision ID: f46fb8558e7e
Revises: eba87f7f4584
Create Date: 2024-11-18 21:18:56.786929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46fb8558e7e'
down_revision = 'eba87f7f4584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter__postings',
    sa.Column('postingId', sa.Integer(), nullable=False),
    sa.Column('recruiterId', sa.Integer(), nullable=False),
    sa.Column('jobTitle', sa.String(length=500), nullable=False),
    sa.Column('jobDescription', sa.String(length=1000), nullable=False),
    sa.Column('jobLink', sa.String(length=1000), nullable=False),
    sa.Column('jobLocation', sa.String(length=500), nullable=False),
    sa.Column('jobPayRate', sa.String(length=120), nullable=False),
    sa.Column('maxHoursAllowed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recruiterId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('postingId', 'recruiterId')
    )
    with op.batch_alter_table('recruiter__postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruiter__postings_jobDescription'), ['jobDescription'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruiter__postings_jobLink'), ['jobLink'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruiter__postings_jobLocation'), ['jobLocation'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruiter__postings_jobPayRate'), ['jobPayRate'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruiter__postings_jobTitle'), ['jobTitle'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiter__postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruiter__postings_jobTitle'))
        batch_op.drop_index(batch_op.f('ix_recruiter__postings_jobPayRate'))
        batch_op.drop_index(batch_op.f('ix_recruiter__postings_jobLocation'))
        batch_op.drop_index(batch_op.f('ix_recruiter__postings_jobLink'))
        batch_op.drop_index(batch_op.f('ix_recruiter__postings_jobDescription'))

    op.drop_table('recruiter__postings')
    # ### end Alembic commands ###
